/**
 * Svelte Integration Types
 *
 * Type definitions specific to the Svelte integration package.
 */

/// <reference lib="dom" />
/// <reference lib="dom.iterable" />

import type { RenderParams, RenderResult } from "@useavalon/core/types";

/**
 * Svelte-specific render parameters
 */
export interface SvelteRenderParams extends RenderParams {
	/**
	 * Svelte component context map
	 */
	context?: Map<string, unknown>;
}

/**
 * Svelte-specific render result
 */
export interface SvelteRenderResult extends RenderResult {
	/**
	 * Head content generated by Svelte component (e.g., svelte:head)
	 */
	head?: string;

	/**
	 * CSS generated by Svelte component
	 */
	css?: string;
}

/**
 * Svelte component module structure
 */
export interface SvelteComponentModule {
	/**
	 * Default export - the Svelte component class
	 */
	default: SvelteComponent;
}

/**
 * Svelte component class/constructor
 */
export interface SvelteComponent {
	/**
	 * Create a new Svelte component instance
	 */
	new (options: SvelteComponentOptions): SvelteComponentInstance;
}

/**
 * Options for creating a Svelte component instance
 */
export interface SvelteComponentOptions {
	/**
	 * Target DOM element for mounting
	 */
	target: HTMLElement;

	/**
	 * Component props
	 */
	props?: Record<string, unknown>;

	/**
	 * Whether to hydrate existing server-rendered content
	 */
	hydrate?: boolean;

	/**
	 * Component context
	 */
	context?: Map<string, unknown>;
}

/**
 * Svelte component instance
 */
export interface SvelteComponentInstance {
	/**
	 * Update component props
	 */
	$set(props: Record<string, unknown>): void;

	/**
	 * Destroy the component instance
	 */
	$destroy(): void;

	/**
	 * Subscribe to component events
	 */
	$on?(event: string, handler: (...args: unknown[]) => void): () => void;
}

/**
 * Svelte SSR render result from svelte/server
 */
export interface SvelteSsrRenderResult {
	/**
	 * Rendered HTML body
	 */
	body: string;

	/**
	 * Head content (from svelte:head)
	 */
	head: string;

	/**
	 * CSS object with code and map
	 */
	css?: {
		code: string;
		map?: string;
	};
}
