/**
 * Static Asset Handler for Nitro
 *
 * This module provides static asset serving capabilities for the Nitro integration,
 * including serving files from the public directory, compiled assets from build output,
 * and support for pre-compressed assets (gzip, brotli).
 *
 * ## Nitro Integration
 *
 * Nitro automatically serves static assets from the `public/` directory at the root path.
 * This module provides:
 * - Route rules generation for cache headers via `createStaticAssetRouteRules()`
 * - MIME type detection and cache control utilities
 * - Support for pre-compressed assets (gzip, brotli)
 * - ETag generation for cache validation
 *
 * ## Configuration
 *
 * Static assets are configured in the Nitro config via `staticAssets` option:
 * ```ts
 * nitro: {
 *   staticAssets: {
 *     publicDir: 'public',
 *     buildDir: 'dist',
 *     compression: true,
 *   },
 * }
 * ```
 *
 * Route rules for caching are automatically generated by `createDefaultStaticAssetRouteRules()`
 * in the config module, or can be customized via `routeRules` in the Nitro config.
 *
 * @module nitro/static-assets
 */

/**
 * Configuration options for static asset serving
 */
export interface StaticAssetConfig {
  /**
   * Directory containing public static assets
   * @default "public"
   */
  publicDir?: string;

  /**
   * Directory containing compiled build output
   * @default "dist"
   */
  buildDir?: string;

  /**
   * Enable serving pre-compressed assets (gzip, brotli)
   * @default true
   */
  compression?: boolean;

  /**
   * Default cache control header for static assets
   * @default "public, max-age=31536000, immutable"
   */
  cacheControl?: string;

  /**
   * Cache control header for mutable assets (HTML, etc.)
   * @default "public, max-age=0, must-revalidate"
   */
  mutableCacheControl?: string;

  /**
   * File extensions considered immutable (hashed filenames)
   * @default [".js", ".css", ".woff", ".woff2", ".ttf", ".eot", ".otf"]
   */
  immutableExtensions?: string[];

  /**
   * Enable ETag generation for cache validation
   * @default true
   */
  etag?: boolean;

  /**
   * Custom headers to add to all static asset responses
   */
  headers?: Record<string, string>;
}

/**
 * Default configuration for static asset serving
 */
export const DEFAULT_STATIC_ASSET_CONFIG: Required<StaticAssetConfig> = {
  publicDir: "public",
  buildDir: "dist",
  compression: true,
  cacheControl: "public, max-age=31536000, immutable",
  mutableCacheControl: "public, max-age=0, must-revalidate",
  immutableExtensions: [".js", ".css", ".woff", ".woff2", ".ttf", ".eot", ".otf"],
  etag: true,
  headers: {},
};

/**
 * MIME type mappings for common file extensions
 */
export const MIME_TYPES: Record<string, string> = {
  // JavaScript
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".cjs": "application/javascript; charset=utf-8",

  // CSS
  ".css": "text/css; charset=utf-8",

  // HTML
  ".html": "text/html; charset=utf-8",
  ".htm": "text/html; charset=utf-8",

  // JSON
  ".json": "application/json; charset=utf-8",

  // Images
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",

  // Fonts
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".eot": "application/vnd.ms-fontobject",

  // Media
  ".mp3": "audio/mpeg",
  ".mp4": "video/mp4",
  ".webm": "video/webm",
  ".ogg": "audio/ogg",
  ".wav": "audio/wav",

  // Documents
  ".pdf": "application/pdf",
  ".xml": "application/xml",
  ".txt": "text/plain; charset=utf-8",
  ".md": "text/markdown; charset=utf-8",

  // Archives
  ".zip": "application/zip",
  ".gz": "application/gzip",
  ".br": "application/br",

  // Source maps
  ".map": "application/json",

  // WebAssembly
  ".wasm": "application/wasm",

  // Manifest
  ".webmanifest": "application/manifest+json",
};

/**
 * Compression encoding mappings
 */
export const COMPRESSION_ENCODINGS: Record<string, string> = {
  ".gz": "gzip",
  ".br": "br",
};

/**
 * Result of resolving a static asset
 */
export interface ResolvedStaticAsset {
  /** Absolute file path */
  filePath: string;
  /** MIME type for Content-Type header */
  mimeType: string;
  /** Content-Encoding if compressed */
  contentEncoding?: string;
  /** Cache-Control header value */
  cacheControl: string;
  /** Whether the asset is immutable (hashed filename) */
  immutable: boolean;
  /** Original file path (before compression resolution) */
  originalPath: string;
}

/**
 * Gets the MIME type for a file based on its extension
 *
 * @param filePath - File path or name
 * @returns MIME type string
 */
export function getMimeType(filePath: string): string {
  const ext = getExtension(filePath);
  return MIME_TYPES[ext] ?? "application/octet-stream";
}

/**
 * Gets the file extension from a path
 *
 * @param filePath - File path
 * @returns Extension including the dot (e.g., ".js")
 */
export function getExtension(filePath: string): string {
  const lastDot = filePath.lastIndexOf(".");
  if (lastDot === -1) return "";
  return filePath.slice(lastDot).toLowerCase();
}

/**
 * Checks if a file path represents an immutable asset (hashed filename)
 *
 * @param filePath - File path to check
 * @param immutableExtensions - Extensions considered immutable
 * @returns True if the asset is immutable
 */
export function isImmutableAsset(
  filePath: string,
  immutableExtensions: string[] = DEFAULT_STATIC_ASSET_CONFIG.immutableExtensions
): boolean {
  const ext = getExtension(filePath);
  if (!immutableExtensions.includes(ext)) {
    return false;
  }

  // Check for hash pattern in filename (e.g., file.abc123.js)
  const hashPattern = /\.[a-f0-9]{8,}\.(?:js|css|woff2?|ttf|eot|otf)$/i;
  return hashPattern.test(filePath);
}

/**
 * Determines the appropriate cache control header for an asset
 *
 * @param filePath - File path
 * @param config - Static asset configuration
 * @returns Cache-Control header value
 */
export function getCacheControl(
  filePath: string,
  config: StaticAssetConfig = {}
): string {
  const mergedConfig = { ...DEFAULT_STATIC_ASSET_CONFIG, ...config };

  if (isImmutableAsset(filePath, mergedConfig.immutableExtensions)) {
    return mergedConfig.cacheControl;
  }

  return mergedConfig.mutableCacheControl;
}

/**
 * Parses the Accept-Encoding header to determine supported compressions
 *
 * @param acceptEncoding - Accept-Encoding header value
 * @returns Array of supported encodings in preference order
 */
export function parseAcceptEncoding(acceptEncoding: string | null): string[] {
  if (!acceptEncoding) return [];

  const encodings: Array<{ encoding: string; quality: number }> = [];

  for (const part of acceptEncoding.split(",")) {
    const [encoding, ...params] = part.trim().split(";");
    let quality = 1;

    for (const param of params) {
      const [key, value] = param.trim().split("=");
      if (key === "q" && value) {
        quality = parseFloat(value);
      }
    }

    if (quality > 0) {
      encodings.push({ encoding: encoding.trim(), quality });
    }
  }

  // Sort by quality (descending)
  encodings.sort((a, b) => b.quality - a.quality);

  return encodings.map((e) => e.encoding);
}

/**
 * Checks if a compressed version of a file exists
 *
 * @param filePath - Original file path
 * @param encoding - Compression encoding to check
 * @returns Path to compressed file if it exists, null otherwise
 */
export async function findCompressedFile(
  filePath: string,
  encoding: string
): Promise<string | null> {
  const extensionMap: Record<string, string> = {
    br: ".br",
    gzip: ".gz",
  };

  const ext = extensionMap[encoding];
  if (!ext) return null;

  const compressedPath = filePath + ext;

  try {
    await Deno.stat(compressedPath);
    return compressedPath;
  } catch {
    return null;
  }
}

/**
 * Resolves a static asset, checking for compressed versions if available
 *
 * @param requestPath - Request URL path
 * @param acceptEncoding - Accept-Encoding header value
 * @param config - Static asset configuration
 * @returns Resolved asset information or null if not found
 */
export async function resolveStaticAsset(
  requestPath: string,
  acceptEncoding: string | null,
  config: StaticAssetConfig = {}
): Promise<ResolvedStaticAsset | null> {
  const mergedConfig = { ...DEFAULT_STATIC_ASSET_CONFIG, ...config };

  // Normalize the request path
  const normalizedPath = requestPath.startsWith("/")
    ? requestPath.slice(1)
    : requestPath;

  // Try public directory first, then build directory
  const directories = [mergedConfig.publicDir, mergedConfig.buildDir];

  for (const dir of directories) {
    const filePath = `${dir}/${normalizedPath}`;

    // Check if the file exists
    try {
      const stat = await Deno.stat(filePath);
      if (!stat.isFile) continue;

      // File exists, check for compressed versions if compression is enabled
      let resolvedPath = filePath;
      let contentEncoding: string | undefined;

      if (mergedConfig.compression && acceptEncoding) {
        const supportedEncodings = parseAcceptEncoding(acceptEncoding);

        // Try brotli first, then gzip
        for (const encoding of supportedEncodings) {
          const compressedPath = await findCompressedFile(filePath, encoding);
          if (compressedPath) {
            resolvedPath = compressedPath;
            contentEncoding = encoding;
            break;
          }
        }
      }

      return {
        filePath: resolvedPath,
        mimeType: getMimeType(filePath), // Use original file for MIME type
        contentEncoding,
        cacheControl: getCacheControl(filePath, mergedConfig),
        immutable: isImmutableAsset(filePath, mergedConfig.immutableExtensions),
        originalPath: filePath,
      };
    } catch {
      // File doesn't exist in this directory, try next
      continue;
    }
  }

  return null;
}

/**
 * Generates an ETag for a file based on its modification time and size
 *
 * @param stat - File stat information
 * @returns ETag string
 */
export function generateETag(stat: Deno.FileInfo): string {
  const mtime = stat.mtime?.getTime() ?? 0;
  const size = stat.size;
  return `"${mtime.toString(16)}-${size.toString(16)}"`;
}

/**
 * Checks if a request can be served with a 304 Not Modified response
 *
 * @param requestHeaders - Request headers
 * @param etag - Current ETag
 * @param lastModified - Last modified date
 * @returns True if 304 response should be sent
 */
export function shouldReturn304(
  requestHeaders: Headers,
  etag: string,
  lastModified: Date | null
): boolean {
  // Check If-None-Match header
  const ifNoneMatch = requestHeaders.get("if-none-match");
  if (ifNoneMatch) {
    // Handle multiple ETags
    const etags = ifNoneMatch.split(",").map((e) => e.trim());
    if (etags.includes(etag) || etags.includes("*")) {
      return true;
    }
  }

  // Check If-Modified-Since header
  const ifModifiedSince = requestHeaders.get("if-modified-since");
  if (ifModifiedSince && lastModified) {
    const ifModifiedDate = new Date(ifModifiedSince);
    if (lastModified <= ifModifiedDate) {
      return true;
    }
  }

  return false;
}

/**
 * Creates response headers for a static asset
 *
 * @param asset - Resolved static asset
 * @param stat - File stat information
 * @param config - Static asset configuration
 * @returns Headers object
 */
export function createStaticAssetHeaders(
  asset: ResolvedStaticAsset,
  stat: Deno.FileInfo,
  config: StaticAssetConfig = {}
): Headers {
  const mergedConfig = { ...DEFAULT_STATIC_ASSET_CONFIG, ...config };
  const headers = new Headers();

  // Content-Type
  headers.set("Content-Type", asset.mimeType);

  // Content-Length
  headers.set("Content-Length", stat.size.toString());

  // Cache-Control
  headers.set("Cache-Control", asset.cacheControl);

  // Content-Encoding (if compressed)
  if (asset.contentEncoding) {
    headers.set("Content-Encoding", asset.contentEncoding);
    // Vary header for proper caching of compressed responses
    headers.set("Vary", "Accept-Encoding");
  }

  // ETag
  if (mergedConfig.etag) {
    headers.set("ETag", generateETag(stat));
  }

  // Last-Modified
  if (stat.mtime) {
    headers.set("Last-Modified", stat.mtime.toUTCString());
  }

  // Custom headers
  for (const [key, value] of Object.entries(mergedConfig.headers)) {
    headers.set(key, value);
  }

  // Security headers for certain file types
  if (asset.mimeType.startsWith("text/html")) {
    headers.set("X-Content-Type-Options", "nosniff");
  }

  return headers;
}

/**
 * Serves a static asset file
 *
 * @param request - HTTP request
 * @param config - Static asset configuration
 * @returns Response or null if asset not found
 */
export async function serveStaticAsset(
  request: Request,
  config: StaticAssetConfig = {}
): Promise<Response | null> {
  const url = new URL(request.url);
  const acceptEncoding = request.headers.get("accept-encoding");

  // Resolve the static asset
  const asset = await resolveStaticAsset(url.pathname, acceptEncoding, config);

  if (!asset) {
    return null;
  }

  // Get file stats
  const stat = await Deno.stat(asset.filePath);

  // Check for 304 Not Modified
  const mergedConfig = { ...DEFAULT_STATIC_ASSET_CONFIG, ...config };
  if (mergedConfig.etag) {
    const etag = generateETag(stat);
    if (shouldReturn304(request.headers, etag, stat.mtime)) {
      return new Response(null, {
        status: 304,
        headers: {
          ETag: etag,
          "Cache-Control": asset.cacheControl,
        },
      });
    }
  }

  // Create response headers
  const headers = createStaticAssetHeaders(asset, stat, config);

  // Handle HEAD requests
  if (request.method === "HEAD") {
    return new Response(null, { status: 200, headers });
  }

  // Read and return the file
  const file = await Deno.readFile(asset.filePath);
  return new Response(file, { status: 200, headers });
}

/**
 * Creates a static asset handler for use with Nitro
 *
 * @param config - Static asset configuration
 * @returns Handler function
 */
export function createStaticAssetHandler(
  config: StaticAssetConfig = {}
): (request: Request) => Promise<Response | null> {
  return (request: Request) => serveStaticAsset(request, config);
}

/**
 * Route rules for static asset caching in Nitro
 *
 * @param config - Static asset configuration
 * @returns Route rules object for Nitro configuration
 */
export function createStaticAssetRouteRules(
  config: StaticAssetConfig = {}
): Record<string, { headers: Record<string, string> }> {
  const mergedConfig = { ...DEFAULT_STATIC_ASSET_CONFIG, ...config };

  return {
    // Immutable assets (hashed filenames)
    "/_nuxt/**": {
      headers: {
        "Cache-Control": mergedConfig.cacheControl,
      },
    },
    "/assets/**": {
      headers: {
        "Cache-Control": mergedConfig.cacheControl,
      },
    },
    "/islands/**": {
      headers: {
        "Cache-Control": mergedConfig.cacheControl,
      },
    },
    "/chunks/**": {
      headers: {
        "Cache-Control": mergedConfig.cacheControl,
      },
    },
    // Mutable assets
    "/**/*.html": {
      headers: {
        "Cache-Control": mergedConfig.mutableCacheControl,
      },
    },
    "/favicon.ico": {
      headers: {
        "Cache-Control": "public, max-age=86400",
      },
    },
  };
}
