[build]
  base = "www/"
  command = "bun install && bun build.mjs"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  BUN_VERSION = "latest"
  NITRO_PRESET = "netlify"

[dev]
  command = "bunx --bun vite"
  targetPort = 8012
  autoLaunch = false

[functions]
  directory = ".netlify/functions-internal"
  node_bundler = "none"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
