[build]
  base = "www/"
  command = "bun install && bunx --bun vite build && node post-build.mjs"
  publish = "dist"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "22"
  BUN_VERSION = "latest"
  NITRO_PRESET = "netlify"
