const APP_INCLUDE = [
	"app/**/*.ts",
	"app/**/*.tsx",
	"app/**/*.d.ts",
	"server/**/*.ts",
	"routes/**/*.ts",
	"middleware/**/*.ts",
];

/** Referenced projects so the editor typechecks each island extension with its JSX runtime. */
const JSX_FRAMEWORKS = [
	{
		filename: "tsconfig.react.json",
		source: "react",
		outDir: ".tsbuild/react",
		globs: ["app/**/*.react.tsx", "app/**/*.react.jsx"],
	},
	{
		filename: "tsconfig.solid.json",
		source: "solid-js",
		outDir: ".tsbuild/solid",
		globs: ["app/**/*.solid.tsx", "app/**/*.solid.jsx"],
	},
	{
		filename: "tsconfig.qwik.json",
		source: "@builder.io/qwik",
		outDir: ".tsbuild/qwik",
		globs: ["app/**/*.qwik.tsx", "app/**/*.qwik.jsx"],
	},
] as const;

function compilerOptions(jsxImportSource: string) {
	return {
		target: "ESNext",
		module: "ESNext",
		moduleResolution: "bundler",
		strict: true,
		esModuleInterop: true,
		skipLibCheck: true,
		allowArbitraryExtensions: true,
		allowImportingTsExtensions: true,
		noEmit: true,
		jsx: "react-jsx",
		// The page shell's JSX. React libraries (Radix/shadcn) typecheck
		// natively under the React engine; under Preact they resolve via compat.
		jsxImportSource,
		paths: {
			"@shared/*": ["./app/shared/*"],
			"@modules/*": ["./app/modules/*"],
		},
	};
}

export function generateTsConfig(core: "preact" | "react" = "preact"): string {
	const tsconfig = {
		compilerOptions: compilerOptions(core),
		include: APP_INCLUDE,
		exclude: JSX_FRAMEWORKS.flatMap((framework) => [...framework.globs]),
		references: JSX_FRAMEWORKS.map((framework) => ({ path: `./${framework.filename}` })),
	};

	return JSON.stringify(tsconfig, null, 2);
}

/** Sibling tsconfigs referenced by `generateTsConfig`. One file per JSX island extension. */
export function generateFrameworkTsConfigs(): Record<string, string> {
	const files: Record<string, string> = {};
	for (const framework of JSX_FRAMEWORKS) {
		files[framework.filename] = JSON.stringify(
			{
				compilerOptions: {
					...compilerOptions(framework.source),
					composite: true,
					noEmit: false,
					declaration: true,
					emitDeclarationOnly: true,
					outDir: framework.outDir,
				},
				include: [...framework.globs, "app/**/*.d.ts"],
			},
			null,
			2,
		);
	}
	return files;
}

export function generateEnvDts(integrations: string[] = []): string {
	const lines: string[] = [
		`/**`,
		` * Auto-generated by create-avalon — do not edit manually.`,
		` *`,
		` * This file provides TypeScript declarations for cross-framework`,
		` * island imports, CSS modules, and Nitro virtual asset manifests.`,
		` * Re-run the scaffold to regenerate after changing integrations.`,
		` */`,
		`/// <reference types="@useavalon/avalon/types" />`,
		``,
	];

	// Cross-framework island module declarations — only for selected integrations.
	// These let TS treat cross-framework files as Preact-compatible components
	// so the island prop and component props work without manual casting.
	const frameworkModules: Record<string, { pattern: string }> = {
		vue: { pattern: "*.vue" },
		svelte: { pattern: "*.svelte" },
		solid: { pattern: "*.solid.tsx" },
		lit: { pattern: "*.lit.ts" },
		qwik: { pattern: "*.qwik.tsx" },
	};

	const selected = Object.entries(frameworkModules).filter(([name]) => integrations.includes(name));

	if (selected.length > 0) {
		for (const [, { pattern }] of selected) {
			lines.push(
				`declare module '${pattern}' {`,
				`\timport type { ComponentType } from 'preact';`,
				`\tconst component: ComponentType<Record<string, unknown>>;`,
				`\texport default component;`,
				`}`,
				``,
			);
		}
	}

	// CSS modules — always included
	lines.push(
		`declare module '*.module.css' {`,
		`\tconst classes: Record<string, string>;`,
		`\texport default classes;`,
		`}`,
		``,
	);

	// Nitro virtual asset manifests — always included
	for (const suffix of ["client", "ssr"]) {
		lines.push(
			`declare module '*?assets=${suffix}' {`,
			`\tconst assets: {`,
			`\t\tcss: Array<{ href: string; [key: string]: string }>;`,
			`\t\tjs: Array<{ href: string; [key: string]: string }>;`,
			`\t\tentry: string;`,
			`\t\tmerge(other: unknown): typeof assets;`,
			`\t};`,
			`\texport default assets;`,
			`}`,
			``,
		);
	}

	return lines.join("\n");
}
