/**
 * @avalon/qwik
 *
 * Qwik integration for Avalon framework
 * Provides server-side rendering and client-side resumability for Qwik components
 *
 * Qwik is fundamentally different from other frameworks:
 * - No hydration step — uses resumability instead
 * - Lazy-loads code at $ boundaries on demand
 * - Serializes state into the DOM for instant resumption
 * - Qwikloader (~1KB) handles global event delegation
 */

import type { Plugin } from "vite";
import type { Integration, IntegrationConfig } from "../core/types.ts";
import { render } from "./server/renderer.ts";
import { getHydrationScript } from "./client/hydration.ts";

/**
 * Qwik integration configuration
 */
const config: IntegrationConfig = {
  name: "qwik",
  fileExtensions: [".tsx", ".jsx", ".ts", ".js"],
  jsxImportSources: ["@builder.io/qwik"],
  detectionPatterns: {
    imports: [
      /^@builder\.io\/qwik$/,
      /^@builder\.io\/qwik\//,
      /from\s+['"]@builder\.io\/qwik['"]/,
      /from\s+['"]@builder\.io\/qwik\/[^'"]+['"]/,
    ],
    content: [
      /\bcomponent\$/,
      /\buseSignal\b/,
      /\buseStore\b/,
      /\buseTask\$/,
      /\buseVisibleTask\$/,
      /\buseResource\$/,
      /\buseContext\b/,
      /\buseContextProvider\b/,
      /\.qwik\./,
    ],
  },
};

/**
 * Qwik integration object
 * Implements the Integration interface
 */
export const qwikIntegration: Integration = {
  name: "qwik",
  version: "0.1.0",

  render,

  getHydrationScript,

  config(): IntegrationConfig {
    return config;
  },

  /**
   * Provides Qwik Vite plugins for islands architecture.
   * 
   * Unlike the official qwikVite plugin which is designed for full Qwik apps,
   * this provides minimal plugins that:
   * 1. Transform .qwik.tsx/.qwik.jsx files using the Qwik optimizer
   * 2. Provide a virtual @qwik-client-manifest module for SSR
   * 
   * Uses 'inline' entry strategy to keep components self-contained without
   * chunk splitting, which works better for islands architecture.
   */
  async vitePlugin(): Promise<Plugin | Plugin[]> {
    const { createOptimizer } = await import("@builder.io/qwik/optimizer");
    
    // Virtual module plugin to provide @qwik-client-manifest for SSR
    // Qwik's server module requires this manifest, but we don't use Qwik's full build system
    const qwikManifestPlugin: Plugin = {
      name: "avalon:qwik-manifest",
      resolveId(id) {
        if (id === "@qwik-client-manifest") {
          return "\0@qwik-client-manifest";
        }
      },
      load(id) {
        if (id === "\0@qwik-client-manifest") {
          // Provide an empty manifest for dev mode
          // In production, this would be generated by the build
          return `export const manifest = { bundles: {}, symbols: {}, mapping: {} };`;
        }
      },
    };

    // Transform plugin for .qwik.tsx/.qwik.jsx files
    // Uses the Qwik optimizer with 'inline' entry strategy
    const qwikTransformPlugin: Plugin = {
      name: "avalon:qwik-transform",
      enforce: "pre",

      async transform(code, id, options) {
        if (!id.includes(".qwik.")) return null;

        const isSSR = options?.ssr === true;

        try {
          const optimizer = await createOptimizer();
          const result = await optimizer.transformModules({
            srcDir: process.cwd(),
            input: [{ path: id, code }],
            sourceMaps: true,
            transpileTs: true,
            transpileJsx: true,
            // Use 'inline' strategy which keeps everything in one file with proper exports
            // This works better for islands architecture than 'hook' which splits into chunks
            entryStrategy: { type: "inline" },
            mode: "dev",
            isServer: isSSR,
          });

          if (result.modules.length > 0) {
            const mainModule = result.modules.find((m) => !m.segment) || result.modules[0];
            return {
              code: mainModule.code,
              map: mainModule.map,
            };
          }
        } catch (e) {
          console.warn("[avalon:qwik-transform] Failed to transform:", id, e);
        }
        return null;
      },
    };

    return [qwikManifestPlugin, qwikTransformPlugin];
  },
};

// Re-export public API
export { render, renderWithErrorBoundary } from "./server/renderer.ts";
export { hydrate, getHydrationScript } from "./client/hydration.ts";
export {
  loadComponent,
  isQwikComponent,
  normalizeProps,
  resolveIslandPath,
} from "./server/utils.ts";

// Re-export types
export type * from "./types.ts";
export type {
  Integration,
  IntegrationConfig,
  RenderParams,
  RenderResult,
} from "../core/types.ts";
