/**
 * @useavalon/qwik
 *
 * Qwik integration for Avalon framework
 * Provides server-side rendering and client-side resumability for Qwik components
 *
 * Qwik is fundamentally different from other frameworks:
 * - No hydration step — uses resumability instead
 * - Lazy-loads code at $ boundaries on demand
 * - Serializes state into the DOM for instant resumption
 * - Qwikloader (~1KB) handles global event delegation
 */

import type { Plugin } from 'vite';
import type { Integration, IntegrationConfig } from '@useavalon/core/types';
import { render } from './server/renderer.ts';
import { getHydrationScript } from './client/hydration.ts';

/**
 * Qwik integration configuration
 */
const config: IntegrationConfig = {
	name: 'qwik',
	fileExtensions: ['.tsx', '.jsx', '.ts', '.js'],
	jsxImportSources: ['@builder.io/qwik'],
	detectionPatterns: {
		imports: [
			/^@builder\.io\/qwik$/,
			/^@builder\.io\/qwik\//,
			/from\s+['"]@builder\.io\/qwik['"]/,
			/from\s+['"]@builder\.io\/qwik\/[^'"]+['"]/,
		],
		content: [
			/\bcomponent\$/,
			/\buseSignal\b/,
			/\buseStore\b/,
			/\buseTask\$/,
			/\buseVisibleTask\$/,
			/\buseResource\$/,
			/\buseContext\b/,
			/\buseContextProvider\b/,
			/\.qwik\./,
		],
	},
};

/**
 * Qwik integration object
 * Implements the Integration interface
 */
export const qwikIntegration: Integration = {
	name: 'qwik',
	version: '0.1.0',

	render,

	getHydrationScript,

	config(): IntegrationConfig {
		return config;
	},

	/**
	 * Provides Qwik Vite plugins for islands architecture.
	 *
	 * Unlike the official qwikVite plugin which is designed for full Qwik apps,
	 * this provides minimal plugins that:
	 * 1. Transform .qwik.tsx/.qwik.jsx files using the Qwik optimizer
	 * 2. Provide a virtual @qwik-client-manifest module for SSR
	 *
	 * Uses 'hoist' entry strategy so QRL handlers are hoisted to the top
	 * level of the module as named exports while staying in the same file.
	 * A middleware intercepts Qwikloader ?qrl= requests and serves the
	 * transformed module so QRL handlers resolve correctly.
	 */
	async vitePlugin(): Promise<Plugin | Plugin[]> {
		const { createOptimizer } = await import('@builder.io/qwik/optimizer');

		// Resolved project root — set by configResolved, used by the transform
		let projectRoot = process.cwd();
		let isDev = true;

		// Virtual module plugin to provide @qwik-client-manifest for SSR
		// Qwik's server module requires this manifest, but we don't use Qwik's full build system
		const qwikManifestPlugin: Plugin = {
			name: 'avalon:qwik-manifest',
			resolveId(id) {
				if (id === '@qwik-client-manifest') {
					return '\0@qwik-client-manifest';
				}
			},
			load(id) {
				if (id === '\0@qwik-client-manifest') {
					// Provide an empty manifest for dev mode
					// In production, this would be generated by the build
					return `export const manifest = { bundles: {}, symbols: {}, mapping: {} };`;
				}
			},
		};

		// Transform plugin for .qwik.tsx/.qwik.jsx files.
		// Uses the Qwik optimizer with 'hoist' entry strategy — QRL handlers
		// are hoisted to the top level as named exports in the same module.
		const qwikTransformPlugin: Plugin = {
			name: 'avalon:qwik-transform',
			enforce: 'pre',

			configResolved(config) {
				projectRoot = config.root;
				isDev = config.command === 'serve';
			},

			async transform(code, id, options) {
				const bareId = id.split('?')[0];
				if (!bareId.includes('.qwik.')) return null;

				const isSSR = options?.ssr === true;

				try {
					const optimizer = await createOptimizer();
					const result = await optimizer.transformModules({
						srcDir: projectRoot,
						input: [{ path: bareId, code }],
						sourceMaps: true,
						transpileTs: true,
						transpileJsx: true,
						entryStrategy: { type: 'hoist' },
						mode: isDev ? 'dev' : 'prod',
						isServer: isSSR,
					});

					if (result.modules.length > 0) {
						const mainModule = result.modules.find(m => !m.segment) || result.modules[0];
						let outputCode = mainModule.code;

						// With 'hoist' strategy, QRL handlers are hoisted to the top
						// level as const declarations but NOT exported. The Qwikloader
						// needs them as named exports. Extract symbol names from
						// inlinedQrl/inlinedQrlDEV calls and append an export statement.
						if (!isSSR) {
							const symbolNames = new Set<string>();
							// Match both dev (inlinedQrlDEV) and prod (qrl/inlinedQrl) patterns
							const qrlPatterns = [
								/inlinedQrlDEV\(\s*(\w+)\s*,\s*"(\w+)"/g,
								/inlinedQrl\(\s*(\w+)\s*,\s*"(\w+)"/g,
								/qrl\(\s*(\w+)\s*,\s*"(\w+)"/g,
							];
							for (const pattern of qrlPatterns) {
								let match;
								while ((match = pattern.exec(outputCode)) !== null) {
									symbolNames.add(match[2]);
								}
							}

							if (symbolNames.size > 0) {
								outputCode += `\nexport { ${[...symbolNames].join(', ')} };\n`;
							}

							// Qwik's SSR wraps useVisibleTask$/useTask$ handlers with
							// _hW (a core task-handler wrapper). The Qwikloader fetches
							// the component module and looks for _hW as a named export.
							// Re-export it from @builder.io/qwik so the runtime finds it.
							if (code.includes('useVisibleTask$') || code.includes('useTask$')) {
								outputCode += `export { _hW } from "@builder.io/qwik";\n`;
							}
						}

						return {
							code: outputCode,
							map: mainModule.map,
						};
					}
				} catch (e) {
					console.warn('[avalon:qwik-transform] Failed to transform:', id, e);
				}
				return null;
			},
		};

		// QRL middleware plugin for dev mode.
		// The Qwikloader fetches QRL handlers via URLs like:
		//   /app/components/Counter.qwik.tsx?qrl=symbolName
		// Vite's dev server doesn't run the transform pipeline for URLs
		// with unknown query parameters. This plugin adds middleware that
		// intercepts ?qrl= requests and serves the transformed base module
		// (which contains all QRL handlers as named exports with hoist strategy).
		const qwikQrlPlugin: Plugin = {
			name: 'avalon:qwik-qrl',
			enforce: 'pre',

			configureServer(server) {
				server.middlewares.use(async (req, res, next) => {
					const url = req.url;
					if (!url || !url.includes('?qrl=')) return next();

					// Strip the ?qrl= query to get the base URL
					const baseUrl = url.split('?')[0];

					try {
						// Use Vite's transformRequest to get the already-transformed module.
						// This returns the same transformed code as the base URL, which
						// with 'hoist' strategy contains all QRL handlers as named exports.
						const result = await server.transformRequest(baseUrl);
						if (result) {
							res.setHeader('Content-Type', 'application/javascript');
							res.setHeader('Cache-Control', 'no-cache');
							res.end(result.code);
							return;
						}
					} catch {
						// Transform failed — fall through to default handling
					}

					next();
				});
			},
		};

		return [qwikManifestPlugin, qwikQrlPlugin, qwikTransformPlugin];
	},
};

// Re-export public API
export { render, renderWithErrorBoundary } from './server/renderer.ts';
export { hydrate, getHydrationScript } from './client/hydration.ts';
export { loadComponent, isQwikComponent, normalizeProps, resolveIslandPath } from './server/utils.ts';

// Re-export types
export type * from './types.ts';
export type { Integration, IntegrationConfig, RenderParams, RenderResult } from '@useavalon/core/types';
