import { join, relative } from '@std/path';
import { walk } from '@std/fs';
import type { ApiRoute, ApiRouteConfig, ApiContext, ApiMethod } from '../schemas/api.ts';
import { methodNotAllowed } from '../helpers/api.ts';

/**
 * Discover all API routes in the src/api directory
 *
 * @warning This function uses dynamic imports and filesystem access.
 *
 * **Deployment Compatibility:**
 * - ✅ Works: Local development, traditional servers (VPS, Docker)
 * - ❌ Limited: Deno Deploy, Vercel, Netlify, Cloudflare Workers
 *
 * For serverless/edge deployments, use `registerApiRoutes()` instead.
 */
export async function discoverApiRoutes(): Promise<ApiRoute[]> {
	const apiDir = join(Deno.cwd(), 'src', 'api');
	const routes: ApiRoute[] = [];

	// Check if API directory exists
	try {
		await Deno.stat(apiDir);
	} catch {
		// API directory doesn't exist, return empty array
		return routes;
	}

	// Walk through all files in the API directory
	for await (const entry of walk(apiDir, {
		exts: ['.ts', '.tsx', '.js'],
		includeDirs: false,
	})) {
		if (entry.isFile) {
			const route = await createApiRoute(entry.path, apiDir);
			if (route) {
				routes.push(route);
			}
		}
	}

	return routes;
}

/**
 * Register API routes explicitly (alternative to discovery for static analysis)
 */
export function registerApiRoutes(routeConfigs: Array<{ path: string; config: ApiRouteConfig }>): ApiRoute[] {
	const routes: ApiRoute[] = [];

	for (const { path, config } of routeConfigs) {
		const { pattern, paramNames } = createUrlPattern(path);

		routes.push({
			pattern,
			config,
			filePath: path,
			paramNames,
		});
	}

	return routes;
}

/**
 * Generate static route registration code for deployment
 *
 * Scans your src/api directory and generates a TypeScript file with
 * static route registration for deployment platforms.
 *
 * @param outputPath Path to write the generated routes file (default: './src/routes.ts')
 * @returns The generated TypeScript code as a string
 */
export async function generateStaticRoutes(outputPath = './src/routes.ts'): Promise<string> {
	const apiDir = join(Deno.cwd(), 'src', 'api');
	const routes: string[] = [];

	// Check if API directory exists
	try {
		await Deno.stat(apiDir);
	} catch {
		console.warn('API directory not found, generating empty routes');
		return generateRouteFile([]);
	}

	// Walk through all files in the API directory
	for await (const entry of walk(apiDir, {
		exts: ['.ts', '.tsx', '.js'],
		includeDirs: false,
	})) {
		if (entry.isFile) {
			const relativePath = relative(apiDir, entry.path);
			const urlPath = filePathToUrlPath(relativePath);
			const importPath = relative(Deno.cwd(), entry.path);
			const routeName = `route_${routes.length}`;

			routes.push(`import ${routeName} from './${importPath.replace(/\\/g, '/')}';`);
			routes.push(`  { path: '${urlPath}', config: ${routeName} },`);
		}
	}

	const code = generateRouteFile(routes);

	await Deno.writeTextFile(outputPath, code);
	console.log(`Generated static routes at: ${outputPath}`);

	return code;
}

function generateRouteFile(routes: string[]): string {
	const imports = routes.filter(line => line.startsWith('import'));
	const routeEntries = routes.filter(line => line.startsWith('  {'));

	return `// Auto-generated static routes for deployment
// Generated by: generateStaticRoutes()

import { registerApiRoutes } from '@avalon/islands/server';
${imports.join('\n')}

export const routes = registerApiRoutes([
${routeEntries.join('\n')}
]);
`;
}

/**
 * Create an API route from a file path
 */
async function createApiRoute(filePath: string, apiDir: string): Promise<ApiRoute | null> {
	try {
		// Get relative path from api directory
		const relativePath = relative(apiDir, filePath);

		// Convert file path to URL pattern
		const urlPath = filePathToUrlPath(relativePath);
		const { pattern, paramNames } = createUrlPattern(urlPath);

		// Import the API handler
		// Convert absolute path to file:// URL to ensure proper resolution
		// when this package is consumed from JSR
		const fileUrl = `file://${filePath}`;
		const module = await import(fileUrl);
		const config: ApiRouteConfig = module.default || module;

		return {
			pattern,
			config,
			filePath: relativePath,
			paramNames,
		};
	} catch (error) {
		console.error(`Failed to load API route from ${filePath}:`, error);
		return null;
	}
}

/**
 * Convert file path to URL path
 * Examples:
 * - users.ts -> /users
 * - users/[id].ts -> /users/:id
 * - users/[id]/posts.ts -> /users/:id/posts
 * - [...slug].ts -> /*slug
 */
function filePathToUrlPath(filePath: string): string {
	// Remove file extension
	let urlPath = filePath.replace(/\.(ts|tsx|js)$/, '');

	// Handle index files
	if (urlPath.endsWith('/index') || urlPath === 'index') {
		urlPath = urlPath.replace(/\/index$|^index$/, '');
	}

	// Convert dynamic segments
	// [param] -> :param
	urlPath = urlPath.replace(/\[([^\]]+)\]/g, ':$1');

	// Convert catch-all segments
	// [...param] -> *param
	urlPath = urlPath.replace(/:\.\.\.([^/]+)/g, '*$1');

	// Ensure leading slash
	if (!urlPath.startsWith('/')) {
		urlPath = '/' + urlPath;
	}

	// Handle root index case
	if (urlPath === '/') {
		return '/';
	}

	return urlPath;
}

/**
 * Create URLPattern and extract parameter names
 */
function createUrlPattern(urlPath: string): { pattern: URLPattern; paramNames: string[] } {
	const paramNames: string[] = [];

	// Extract parameter names from the path
	const paramMatches = urlPath.match(/:([^/]+)/g);
	if (paramMatches) {
		for (const match of paramMatches) {
			paramNames.push(match.substring(1)); // Remove ':' prefix
		}
	}

	// Handle catch-all parameters
	const catchAllMatches = urlPath.match(/\*([^/]+)/g);
	if (catchAllMatches) {
		for (const match of catchAllMatches) {
			paramNames.push(match.substring(1)); // Remove '*' prefix
		}
	}

	// Convert to URLPattern syntax
	let patternPath = urlPath;

	// Convert :param to :param
	patternPath = patternPath.replace(/:([^/]+)/g, ':$1');

	// Convert *param to *
	patternPath = patternPath.replace(/\*[^/]+/g, '*');

	const pattern = new URLPattern({
		pathname: '/api' + patternPath,
	});

	return { pattern, paramNames };
}

/**
 * Extract parameters from matched URL
 */
function extractParams(pattern: URLPattern, url: URL, paramNames: string[]): Record<string, string> {
	const params: Record<string, string> = {};

	const result = pattern.exec(url);
	if (result?.pathname?.groups) {
		// Map URLPattern groups to our parameter names
		const groups = result.pathname.groups;
		let paramIndex = 0;

		for (const [key, value] of Object.entries(groups)) {
			if (key !== '0' && value !== undefined) {
				// Skip full match
				if (paramIndex < paramNames.length) {
					params[paramNames[paramIndex]] = value;
					paramIndex++;
				}
			}
		}
	}

	return params;
}

/**
 * Handle API request
 */
export async function handleApiRequest(request: Request, routes: ApiRoute[]): Promise<Response> {
	const url = new URL(request.url);

	// Find matching route
	const matchedRoute = routes.find(route => route.pattern.test(url));

	if (!matchedRoute) {
		return new Response(JSON.stringify({ error: 'API route not found' }), {
			status: 404,
			headers: { 'Content-Type': 'application/json' },
		});
	}

	// Extract parameters
	const params = extractParams(matchedRoute.pattern, url, matchedRoute.paramNames);

	// Parse query parameters
	const query: Record<string, string | string[]> = {};
	for (const [key, value] of url.searchParams.entries()) {
		if (query[key]) {
			if (Array.isArray(query[key])) {
				(query[key] as string[]).push(value);
			} else {
				query[key] = [query[key] as string, value];
			}
		} else {
			query[key] = value;
		}
	}

	// Create context
	const context: ApiContext = {
		request,
		url,
		params,
		query,
	};

	try {
		const { config } = matchedRoute;

		// Handle single handler function
		if (typeof config === 'function') {
			return await config(context);
		}

		// Handle method-specific handlers
		const method = request.method as ApiMethod;
		const handler = config[method];

		if (!handler) {
			// Method not allowed
			const allowedMethods = Object.keys(config).filter(key => config[key as ApiMethod]);
			return methodNotAllowed(allowedMethods);
		}

		return await handler(context);
	} catch (error) {
		console.error('API route error:', error);
		return new Response(JSON.stringify({ error: 'Internal Server Error' }), {
			status: 500,
			headers: { 'Content-Type': 'application/json' },
		});
	}
}
