import { join, relative } from 'node:path';
import { stat as fsStat, writeFile } from 'node:fs/promises';
import { walk } from '../utils/fs.ts';
import type { ApiRoute, ApiRouteConfig, ApiContext, ApiMethod } from '../schemas/api.ts';
import type { MiddlewareContext } from '../nitro/middleware-adapter.ts';
import { methodNotAllowed } from '../core/api/api.ts';

/**
 * Discover all API routes in the src/api directory
 *
 * @deprecated This function is deprecated. API routes should be placed in the
 * `api/` directory at the project root and are auto-discovered by Nitro.
 * 
 * For Nitro-based routing:
 * - Create files in `api/` directory (e.g., `api/hello.ts`)
 * - Use `defineEventHandler` from h3 for handlers
 * - Nitro will auto-discover and register routes
 *
 * @warning This function uses dynamic imports and filesystem access.
 *
 * **Deployment Compatibility:**
 * - ✅ Works: Local development, traditional servers (VPS, Docker)
 * - ❌ Limited: Deno Deploy, Vercel, Netlify, Cloudflare Workers
 *
 * For serverless/edge deployments, use Nitro's native routing instead.
 */
export async function discoverApiRoutes() {
	const apiDir = join(process.cwd(), 'src', 'api');
	const routes: ApiRoute[] = [];

	// Check if API directory exists
	try {
		await fsStat(apiDir);
	} catch {
		// API directory doesn't exist, return empty array
		return routes;
	}

	// Walk through all files in the API directory
	for await (const entry of walk(apiDir, {
		exts: ['.ts', '.tsx', '.js'],
		includeDirs: false,
	})) {
		if (entry.isFile) {
			const route = await createApiRoute(entry.path, apiDir);
			if (route) {
				routes.push(route);
			}
		}
	}

	return routes;
}

/**
 * Register API routes explicitly (alternative to discovery for static analysis)
 */
export function registerApiRoutes(routeConfigs: Array<{ path: string; config: ApiRouteConfig }>) {
	const routes: ApiRoute[] = [];

	for (const { path, config } of routeConfigs) {
		const { pattern, paramNames } = createUrlPattern(path);

		routes.push({
			pattern,
			config,
			filePath: path,
			paramNames,
		});
	}

	return routes;
}

/**
 * Generate static route registration code for deployment
 *
 * Scans your src/api directory and generates a TypeScript file with
 * static route registration for deployment platforms.
 *
 * @param outputPath Path to write the generated routes file (default: './src/routes.ts')
 * @returns The generated TypeScript code as a string
 */
export async function generateStaticRoutes(outputPath = './src/routes.ts') {
	const apiDir = join(process.cwd(), 'src', 'api');
	const routes: string[] = [];

	// Check if API directory exists
	try {
		await fsStat(apiDir);
	} catch {
		console.warn('API directory not found, generating empty routes');
		return generateRouteFile([]);
	}

	// Walk through all files in the API directory
	for await (const entry of walk(apiDir, {
		exts: ['.ts', '.tsx', '.js'],
		includeDirs: false,
	})) {
		if (entry.isFile) {
			const relativePath = relative(apiDir, entry.path);
			const urlPath = filePathToUrlPath(relativePath);
			const importPath = relative(process.cwd(), entry.path);
			const routeName = `route_${routes.length}`;

			routes.push(`import ${routeName} from './${importPath.replace(/\\/g, '/')}';`);
			routes.push(`  { path: '${urlPath}', config: ${routeName} },`);
		}
	}

	const code = generateRouteFile(routes);

	await writeFile(outputPath, code);
	console.log(`Generated static routes at: ${outputPath}`);

	return code;
}

function generateRouteFile(routes: string[]) {
	const imports = routes.filter(line => line.startsWith('import'));
	const routeEntries = routes.filter(line => line.startsWith('  {'));

	return `// Auto-generated static routes for deployment
// Generated by: generateStaticRoutes()

import { registerApiRoutes } from '@avalon/islands/server';
${imports.join('\n')}

export const routes = registerApiRoutes([
${routeEntries.join('\n')}
]);
`;
}

/**
 * Create an API route from a file path
 */
async function createApiRoute(filePath: string, apiDir: string) {
	try {
		// Get relative path from api directory
		const relativePath = relative(apiDir, filePath);

		// Convert file path to URL pattern
		const urlPath = filePathToUrlPath(relativePath);
		const { pattern, paramNames } = createUrlPattern(urlPath);

		// Import the API handler
		// Convert absolute path to file:// URL to ensure proper resolution
		// when this package is consumed from JSR
		const fileUrl = `file://${filePath}`;
		const module = await import(fileUrl);
		const config: ApiRouteConfig = module.default || module;

		return {
			pattern,
			config,
			filePath: relativePath,
			paramNames,
		};
	} catch (error) {
		console.error(`Failed to load API route from ${filePath}:`, error);
		return null;
	}
}

/**
 * Convert file path to URL path
 * Examples:
 * - users.ts -> /users
 * - users/[id].ts -> /users/:id
 * - users/[id]/posts.ts -> /users/:id/posts
 * - [...slug].ts -> /*slug
 */
function filePathToUrlPath(filePath: string) {
	// Remove file extension
	let urlPath = filePath.replace(/\.(ts|tsx|js)$/, '');

	// Handle index files
	if (urlPath.endsWith('/index') || urlPath === 'index') {
		urlPath = urlPath.replace(/\/index$|^index$/, '');
	}

	// Convert dynamic segments
	// [param] -> :param
	urlPath = urlPath.replace(/\[([^\]]+)\]/g, ':$1');

	// Convert catch-all segments
	// [...param] -> *param
	urlPath = urlPath.replace(/:\.\.\.([^/]+)/g, '*$1');

	// Ensure leading slash
	if (!urlPath.startsWith('/')) {
		urlPath = '/' + urlPath;
	}

	// Handle root index case
	if (urlPath === '/') {
		return '/';
	}

	return urlPath;
}

/**
 * Create URLPattern and extract parameter names
 */
function createUrlPattern(urlPath: string) {
	const paramNames: string[] = [];

	// Extract parameter names from the path
	const paramMatches = urlPath.match(/:([^/]+)/g);
	if (paramMatches) {
		for (const match of paramMatches) {
			paramNames.push(match.substring(1)); // Remove ':' prefix
		}
	}

	// Handle catch-all parameters
	const catchAllMatches = urlPath.match(/\*([^/]+)/g);
	if (catchAllMatches) {
		for (const match of catchAllMatches) {
			paramNames.push(match.substring(1)); // Remove '*' prefix
		}
	}

	// Convert to URLPattern syntax
	let patternPath = urlPath;

	// Convert :param to :param
	patternPath = patternPath.replace(/:([^/]+)/g, ':$1');

	// Convert *param to *
	patternPath = patternPath.replace(/\*[^/]+/g, '*');

	const pattern = new URLPattern({
		pathname: '/api' + patternPath,
	});

	return { pattern, paramNames };
}

/**
 * Extract parameters from matched URL
 */
function extractParams(pattern: URLPattern, url: URL, paramNames: string[]) {
	const params: Record<string, string> = {};

	const result = pattern.exec(url);
	if (result?.pathname?.groups) {
		// Map URLPattern groups to our parameter names
		const groups = result.pathname.groups;
		let paramIndex = 0;

		for (const [key, value] of Object.entries(groups)) {
			if (key !== '0' && value !== undefined) {
				// Skip full match
				if (paramIndex < paramNames.length) {
					params[paramNames[paramIndex]] = value;
					paramIndex++;
				}
			}
		}
	}

	return params;
}

/**
 * Handle API request with middleware support
 *
 * @param request - The HTTP request object
 * @param routes - Array of discovered API routes
 * @param middlewareContext - Optional middleware context from middleware execution
 * @returns Response object
 *
 * Requirements: 3.1, 3.3, 3.4, 5.2
 */
export async function handleApiRequest(
	request: Request,
	routes: ApiRoute[],
	middlewareContext?: MiddlewareContext
): Promise<Response> {
	const url = new URL(request.url);

	// Find matching route
	const matchedRoute = routes.find(route => route.pattern.test(url));

	if (!matchedRoute) {
		return new Response(JSON.stringify({ error: 'API route not found' }), {
			status: 404,
			headers: { 'Content-Type': 'application/json' },
		});
	}

	// Extract parameters - prioritize middleware context over fresh extraction
	// This ensures middleware-processed parameters (e.g., validated, transformed) are used
	const params = middlewareContext?.params || extractParams(matchedRoute.pattern, url, matchedRoute.paramNames);

	// Parse query parameters - prioritize middleware context over fresh parsing
	// This ensures middleware-processed query params (e.g., validated, transformed) are used
	const query = middlewareContext?.query || parseQueryParameters(url);

	// Create API context with middleware integration
	const context: ApiContext = {
		request: middlewareContext?.request || request, // Use middleware-processed request if available
		url: middlewareContext?.url || url, // Use middleware-processed URL if available
		params,
		query,
		// Include middleware state and locals for API handlers to access
		...(middlewareContext && {
			state: middlewareContext.state,
			locals: middlewareContext.locals,
		}),
	};

	try {
		const { config } = matchedRoute;

		// Handle single handler function
		if (typeof config === 'function') {
			return await config(context);
		}

		// Handle method-specific handlers
		const method = request.method as ApiMethod;
		const handler = config[method];

		if (!handler) {
			// Method not allowed - return available methods
			const allowedMethods = Object.keys(config).filter(key => config[key as ApiMethod]);
			return methodNotAllowed(allowedMethods);
		}

		return await handler(context);
	} catch (error) {
		console.error('API route error:', error);

		// Enhanced error handling with middleware context information
		const errorResponse: Record<string, unknown> = {
			error: 'Internal Server Error',
		};

		// Add development mode details if available
		if (middlewareContext?.locals?.developmentMode) {
			errorResponse.details = error instanceof Error ? error.message : String(error);
			errorResponse.route = matchedRoute.filePath;
		}

		return new Response(JSON.stringify(errorResponse), {
			status: 500,
			headers: { 'Content-Type': 'application/json' },
		});
	}
}

/**
 * Parse query parameters from URL
 * Handles multiple values for the same parameter
 */
function parseQueryParameters(url: URL) {
	const query: Record<string, string | string[]> = {};

	for (const [key, value] of url.searchParams.entries()) {
		if (query[key]) {
			// Convert to array if multiple values exist
			if (Array.isArray(query[key])) {
				(query[key] as string[]).push(value);
			} else {
				query[key] = [query[key] as string, value];
			}
		} else {
			query[key] = value;
		}
	}

	return query;
}
