/**
 * Auto-generated by Avalon — do not edit manually.
 *
 * This file provides TypeScript declarations for cross-framework
 * island imports, CSS modules, and Nitro virtual asset manifests.
 * Virtual module types (virtual:avalon/*) are provided by the
 * framework via @useavalon/avalon/types.
 */
/// <reference types="@useavalon/avalon/types" />

declare module "*.vue" {
	import type { ComponentType } from "preact";

	const component: ComponentType<Record<string, unknown>>;
	export default component;
}

declare module "*.svelte" {
	import type { ComponentType } from "preact";

	const component: ComponentType<Record<string, unknown>>;
	export default component;
}

declare module "*.solid.tsx" {
	import type { ComponentType } from "preact";

	const component: ComponentType<Record<string, unknown>>;
	export default component;
}

declare module "*.lit.ts" {
	import type { ComponentType } from "preact";

	const component: ComponentType<Record<string, unknown>>;
	export default component;
}

declare module "*.qwik.tsx" {
	import type { ComponentType } from "preact";

	const component: ComponentType<Record<string, unknown>>;
	export default component;
}

declare module "*.module.css" {
	const classes: Record<string, string>;
	export default classes;
}

declare module "*?assets=client" {
	const assets: {
		css: Array<{ href: string; [key: string]: string }>;
		js: Array<{ href: string; [key: string]: string }>;
		entry: string;
		merge(other: unknown): typeof assets;
	};
	export default assets;
}

declare module "*?assets=ssr" {
	const assets: {
		css: Array<{ href: string; [key: string]: string }>;
		js: Array<{ href: string; [key: string]: string }>;
		entry: string;
		merge(other: unknown): typeof assets;
	};
	export default assets;
}

// Pagefind Component UI custom elements
interface PagefindModalElement extends HTMLElement {
	open(): void;
}

declare global {
	interface HTMLElementTagNameMap {
		"pagefind-modal": PagefindModalElement;
	}
}

declare namespace preact.JSX {
	interface IntrinsicElements {
		"pagefind-modal": preact.JSX.HTMLAttributes<PagefindModalElement>;
		"pagefind-modal-trigger": Record<string, unknown>;
		"pagefind-searchbox": Record<string, unknown>;
	}
}
